language: cpp
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9
      - gcc-4.9
install:
  - svn checkout https://github.com/Tencent/rapidjson/trunk/include/rapidjson
script:
  - g++-4.9 main.cpp Solver.h UnarySlot.h -std=c++11
